# Generated by Django 6.0.4 on 2026-05-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstop',
            name='opis_truckstop_id',
            field=models.IntegerField(unique=True),
        ),
    ]
